### ISSUE TITLE
Error when pulling from confluent hub

### ISSUE THREAD

**Issue by FrankMormino** [C0urante/kafka-connect-reddit#15]
See error below:

Command: `RUN confluent-hub install --no-prompt c0urante/kafka-connect-reddit:0.1.3`

```
Step 4/19 : RUN confluent-hub install --no-prompt c0urante/kafka-connect-reddit:0.1.3
 ---> Running in fd70d7558380
Running in a "--no-prompt" mode
Unable to find a component

Error: Component not found, specify either valid name from Confluent Hub in format: <owner>/<name>:<version:latest> or path to a local file
The command '/bin/sh -c confluent-hub install --no-prompt c0urante/kafka-connect-reddit:0.1.3' returned a non-zero code: 1

```

**Comment by C0urante** [comment]
`C0urante` should be capitalized.

**Comment by FrankMormino** [comment]
Out of all the things I've had to do to get this to run locally - instead of just blindly copying and pasting from here lol https://www.confluent.io/hub/C0urante/kafka-connect-reddit thank you so much! 

FYI - the copy on the site copies it like this - `confluent-hub install c0urante/kafka-connect-reddit:0.1.3`
