### ISSUE TITLE
The connector seems to be missing from confluent hub

### ISSUE THREAD

**Issue by Haarolean** [C0urante/kafka-connect-reddit#18]
Hi, it seems the connector is now missing from confluent hub.
Also, the link in the readme is 404.

Is that possible to fix it?

Thank you.

**Comment by C0urante** [comment]
I've removed the Confluent Hub-related installation instructions from the README in b92eb696f2020960fcba944022455a454a4c72c2.

I don't think it's going to be put back on CHub any time soon. Feel free to reach out to Confluent if this is an issue.

**Comment by Haarolean** [comment]
@C0urante is that possible to publish a built jar/zip to github releases page? So we don't have to build it manually.

**Comment by C0urante** [comment]
That would be fine by me, but I don't have the time to look into implementing that myself. I'd be happy to review a PR if anyone else wants to give it a shot.
